version: '3'

services:

  blog:
    build: .
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=root
      - database__connection__database=blog
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
